-- Add password_must_change field to users table
ALTER TABLE users ADD COLUMN IF NOT EXISTS password_must_change BOOLEAN DEFAULT false;

-- Create default admin user (username: admin, password: admin)
-- Password hash for 'admin' using Argon2id
-- This will be generated by the application on first startup
-- Users will be prompted to change password on first login
INSERT INTO users (
    email,
    username,
    password_hash,
    provider,
    full_name,
    is_active,
    is_admin,
    email_verified,
    password_must_change
)
VALUES (
    'admin@nomdb.local',
    'admin',
    -- This is a placeholder - will be set by application on startup
    NULL,
    'local',
    'Default Admin',
    true,
    true,
    true,
    true
)
ON CONFLICT (email) DO NOTHING;
